# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rd4_wrappers", use_symbols = TRUE, package_name = "rd4")

#' @docType package
#' @usage NULL
#' @useDynLib rd4, .registration = TRUE
NULL

#' D4SourceEnv environment
#'
#' Environment with bindings to functions for opening a connection to a D4 file and querying the file. 
#' Generated by `rextendr` to expose bindings into Rust functions. Most users should not use this enviornment directly, 
#' but should use `D4Source` and associated methods instead. In particular, documentation is provided along with `
#' D4Source` and its methods.
#' 
#' @export
D4SourceEnv <- new.env(parent = emptyenv())

D4SourceEnv$new <- function(source) .Call(wrap__D4SourceEnv__new, source)

D4SourceEnv$get_source <- function() .Call(wrap__D4SourceEnv__get_source, self)

D4SourceEnv$get_chroms <- function() .Call(wrap__D4SourceEnv__get_chroms, self)

D4SourceEnv$get_tracks <- function() .Call(wrap__D4SourceEnv__get_tracks, self)

D4SourceEnv$query <- function(chr, left, right, track) .Call(wrap__D4SourceEnv__query, self, chr, left, right, track)

D4SourceEnv$mean <- function(chr, left, right, track) .Call(wrap__D4SourceEnv__mean, self, chr, left, right, track)

D4SourceEnv$median <- function(chr, left, right, track) .Call(wrap__D4SourceEnv__median, self, chr, left, right, track)

D4SourceEnv$histogram <- function(chr, left, right, track, min, max) .Call(wrap__D4SourceEnv__histogram, self, chr, left, right, track, min, max)

D4SourceEnv$percentile <- function(chr, left, right, track, percentile) .Call(wrap__D4SourceEnv__percentile, self, chr, left, right, track, percentile)

D4SourceEnv$resample <- function(chr, left, right, track, method, bin_size, allow_bin_size_adjustment) .Call(wrap__D4SourceEnv__resample, self, chr, left, right, track, method, bin_size, allow_bin_size_adjustment)

#' @rdname D4SourceEnv
#' @usage NULL
#' @export
`$.D4SourceEnv` <- function (self, name) { func <- D4SourceEnv[[name]]; environment(func) <- environment(); func }

#' @export
`[[.D4SourceEnv` <- `$.D4SourceEnv`

#' HistogramEnv Environment
#' 
#' Environment with bindings to functions for accessing the attributes of a histogram. Generated by `rextendr` to 
#' expose bindings into Rust functions. Most users should not use this environment directly, but should instead call
#' S3 methods on a `D4Source` object to return features of the distribution.
#' @export
HistogramEnv <- new.env(parent = emptyenv())

HistogramEnv$value_count <- function(value) .Call(wrap__HistogramEnv__value_count, self, value)

HistogramEnv$total_count <- function() .Call(wrap__HistogramEnv__total_count, self)

HistogramEnv$value_fraction <- function(value) .Call(wrap__HistogramEnv__value_fraction, self, value)

HistogramEnv$fraction_below <- function(value) .Call(wrap__HistogramEnv__fraction_below, self, value)

HistogramEnv$mean <- function() .Call(wrap__HistogramEnv__mean, self)

HistogramEnv$percentile <- function(percentile) .Call(wrap__HistogramEnv__percentile, self, percentile)

HistogramEnv$median <- function() .Call(wrap__HistogramEnv__median, self)

HistogramEnv$std <- function() .Call(wrap__HistogramEnv__std, self)

#' @rdname HistogramEnv
#' @usage NULL
#' @export
`$.HistogramEnv` <- function (self, name) { func <- HistogramEnv[[name]]; environment(func) <- environment(); func }

#' @export
`[[.HistogramEnv` <- `$.HistogramEnv`

#' QueryEnv environment
#' 
#' Environment with bindings to functions for accessing the parameters of a query. Generated by `rextendr` to expose 
#' bindings into Rust functions. Most users should not use this environment directly, but should instead access the 
#' $query attribute of a query result.
#' @export
QueryEnv <- new.env(parent = emptyenv())

QueryEnv$chr <- function() .Call(wrap__QueryEnv__chr, self)

QueryEnv$left <- function() .Call(wrap__QueryEnv__left, self)

QueryEnv$right <- function() .Call(wrap__QueryEnv__right, self)

#' @rdname QueryEnv
#' @usage NULL
#' @export
`$.QueryEnv` <- function (self, name) { func <- QueryEnv[[name]]; environment(func) <- environment(); func }

#' @export
`[[.QueryEnv` <- `$.QueryEnv`

#' QueryResultEnv Environment
#'
#' Environment with bindings to functions for extracting attributes from a query result. Generated by `rextendr` to 
#' expose bindings into Rust functions. Most users should not use this environment directly, but should instead 
#' access attributes of the list returned by `query()`.
#' @export
QueryResultEnv <- new.env(parent = emptyenv())

QueryResultEnv$results <- function() .Call(wrap__QueryResultEnv__results, self)

QueryResultEnv$query <- function() .Call(wrap__QueryResultEnv__query, self)

QueryResultEnv$source <- function() .Call(wrap__QueryResultEnv__source, self)

QueryResultEnv$track <- function() .Call(wrap__QueryResultEnv__track, self)

QueryResultEnv$bin_size <- function() .Call(wrap__QueryResultEnv__bin_size, self)

#' @rdname QueryResultEnv
#' @usage NULL
#' @export
`$.QueryResultEnv` <- function (self, name) { func <- QueryResultEnv[[name]]; environment(func) <- environment(); func }

#' @export
`[[.QueryResultEnv` <- `$.QueryResultEnv`

